[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "urdfit"
version = "0.0.1"
description = "Fitting URDF Parameters via Differentiable Simulation"

[tool.setuptools.packages.find]
include = ["urdfit"]
