services:
  mujoco-id:
    environment:
      - DISPLAY=novnc:0.0 
      - XLA_FLAGS=--xla_gpu_triton_gemm_any=true
      - MUJOCO_GL=egl
    volumes:
      - ../.:/root/Humanoid-MuJoCo-Inverse-Dynamics
    image: "mcgillrobotics/mujoco:id"
    command: bash -c "tail -f /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  novnc:
    image: theasp/novnc:latest
    ports:
      - "8080:8080"
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=3000
      - DISPLAY_HEIGHT=1500 #need to adjust based off height and width of your screen, going for bigger values is typically recommended.