services:
  mujoco:
    environment:
      - DISPLAY=novnc:0.0 
      - RENDER_SIM=false # change if using novnc
      - XLA_FLAGS=--xla_gpu_triton_gemm_any=true
    volumes:
      - ../.:/root/Humanoid-MuJoCo
    image: "mcgillrobotics/mujoco:latest"
    command: bash -c "pip3 install git+https://github.com/mcgill-robotics/Humanoid-rl-baselines3-zoo.git@master && tail -f /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # novnc:
  #   image: theasp/novnc:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - RUN_XTERM=no
  #     - DISPLAY_WIDTH=6000
  #     - DISPLAY_HEIGHT=3000 #need to adjust based off height and width of your screen, going for bigger values is typically recommended.