version: '3.8'
services:
  urdfit:
    environment:
      - DISPLAY=novnc:0.0 
      - XLA_FLAGS=--xla_gpu_triton_gemm_any=true
      - MUJOCO_GL=egl
    image: "urdfit:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../.:/URDFit
    command: bash -c "tail -f /dev/null"
    container_name: urdfit
    # network_mode: host # NOTE: uncomment this line if you want to use the MPC server for ROS, keep it commented if you want to use the GUI

# COMMENT OUT TO RUN SERVER, UNCOMMMENT TO RENDER ROBOT STATE
  novnc:
    image: theasp/novnc:latest
    ports:
      - "8080:8080"
    environment:
      - RUN_XTERM=no
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080 #need to adjust based off height and width of your screen, going for bigger values is typically recommended.
      - FRAMERATE=60
      - ENABLE_WEBSOCKET_COMPRESSION=true